# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# BMVC2021 colours:
# #9E005D
# 158, 0, 93
# #7F004B
# #5F003B
# #DC0082


timezone: Europe/London
title: BMVA Computer Vision Summer School
formatted-title: BMVA Computer Vision Summer School
brand: CVSS&thinsp;2024
short-title: "CVSS 2024"
host-name: Durham University
conf_year: 2024
email: bmva-cvss@durham.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  The website for the 27<sup>th</sup> BMVA Computer Vision Summer School 2024, 15<sup>th</sup> - 19<sup>th</sup> July 2024.
#baseurl: "/BMVC2021" #"/~nc537/bmvc_test" # "/bmva-website" # the subpath of your site, e.g. /blog
#url: "https://britishmachinevisionassociation.github.io" #"http://cs.bath.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/"
#url: "http://bmvc2021.ndfcampbell.org"
baseurl: ""
#url: "http://127.0.0.1:4000"
url: "https://cvss.bmva.org/"
# "https://www.bmvc2021.com"
conf-url: "https://cvss.bmva.org/"
chat-url: "https://chat.cvss.bmva.org/"
logo: "/assets/images/layout/cvss_logo_2024.png"
logo-host: "/assets/images/layout/durham-uni-trans.png"
logo-host-alt: "/assets/images/layout/durham-uni-purple.png"
logo-link: "https://vivid.webspace.durham.ac.uk/"
payment-link: "https://bmva.charitysuite.com/events/dpcdw95c?tickets=FoGDO4icYJK1qnal"
pc-email: "bmva-cvss@durham.ac.uk"
twitter_username: BmvaCvss
#github_username:  BritishMachineVisionAssociation
#facebook_username: thebmva
#youtube_channel: channel/UCBDkH5yK4GyVoRkV8lYdwdw1

deadline-time: "23:59 GMT"

cmt-url: "#"
bmva-event-url: "https://britishmachinevisionassociation.github.io/meetings/21-09-06-september-event"

dates:  15<sup>th</sup> - 19<sup>th</sup> July 2024

author: BMVC PCs

#flickr_user: '131006004@N06'
#flickr_api_key: adb4be93419edab991522b4fa92b7029

# Handling Reading
safe: true
encoding: utf-8
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  # - jekyll-sitemap


#  - jekyll-liquid


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/multipagethumb.sh
  - assets/thumbnail_script.sh
  - copy_to_aws.sh
  - old/
  - conference/
  - programme/paper-awards.md
  - people/reviewer.md
  - people/area-chairs.md
  - old_index.md
  - authors/instructions-for-presenting-authors.md

#  - attending/

#main_sponsors:
#  - name: IAPR
#    url: http://www.iapr.org/
#    logo: /img/affiliates/logo-iapr.png
#sponsors:
#  - name: BCS
#    url: http://bcs.org.uk/
#    logo: /img/affiliates/logo-bcs.png
#  - name: IET
#    url: http://www.theiet.org/
#    logo: /img/affiliates/logo-iet.jpg
#  - name: UKIVA
#    url: http://www.ukiva.org/
#    logo: /img/affiliates/logo-ukiva.jpg
#  - name: AVA
#    url: http://www.theava.net/
#    logo: /img/affiliates/logo-ava.jpg
